package dev.graceskw.backend.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import dev.graceskw.backend.dto.JobDTO;
import dev.graceskw.backend.entity.JobEntity;
import dev.graceskw.backend.enums.JobStatus;
import dev.graceskw.backend.repository.JobRepository;
import lombok.extern.slf4j.Slf4j;

@Service
@Slf4j
public class JobService {
    @Autowired
    private JobRepository jobRepository;

    public JobEntity saveJob(JobDTO jobRequest) {
        JobEntity savedJob = new JobEntity();
        savedJob.setJobPosition(jobRequest.getJobPosition().trim());
        savedJob.setCompanyName(jobRequest.getCompanyName().trim());
        savedJob.setDeadline(java.time.LocalDateTime.parse(jobRequest.getDeadline()));
        savedJob.setJobURL(jobRequest.getJobURL().trim());
        if (jobRequest.getJobDescription() != null) {
            savedJob.setJobDescription(jobRequest.getJobDescription().trim());
        }
        if (jobRequest.getJobStatus() != null || !jobRequest.getJobStatus().isBlank()) {
        savedJob.setJobStatus(JobStatus.valueOf(jobRequest.getJobStatus().trim()));
        }   
        if (jobRequest.getNotes() != null) {
            savedJob.setNotes(jobRequest.getNotes());
        }
        if (jobRequest.getDateApplied() != null) {
            savedJob.setDateApplied(java.time.LocalDateTime.parse(jobRequest.getDateApplied()));
        }

        jobRepository.save(savedJob);
        log.info("Job created successfully with ID: {}", savedJob.getJobId());
        return savedJob;
    }

    public JobEntity getJobById(Long id) {
        // Optional<JobEntity> jobOpt = jobRepository.findByid(id);
        // if (!jobOpt.isPresent()) {
        //     log.error("Job not found with ID: {}", id);
        //     return null;
        // }
        return jobRepository.findByJobId(id).orElse(null);
    }

    public void deleteJobById(Long id) {
        // deleteById is auto generated by JpaRepository (bcuz repository extends jpareporistory), Id == the one tagged by @Id in entity, same method name regardless of field name
        jobRepository.deleteById(id);
        log.info("Job deleted successfully with ID: {}", id);
    }

    public List<JobEntity> getAllJobs() {
        return jobRepository.findAll();
    }

    public JobEntity updateJob(JobDTO jobRequest, JobEntity existingJob) {
        existingJob.setJobPosition(jobRequest.getJobPosition().trim());
        existingJob.setCompanyName(jobRequest.getCompanyName().trim());
        existingJob.setDeadline(java.time.LocalDateTime.parse(jobRequest.getDeadline()));
        existingJob.setJobURL(jobRequest.getJobURL().trim());
        if (jobRequest.getJobStatus() != null) {
            existingJob.setJobStatus(JobStatus.valueOf(jobRequest.getJobStatus()));
        }
        if (jobRequest.getJobDescription() != null) {
            existingJob.setJobDescription(jobRequest.getJobDescription());
        }
        if (jobRequest.getNotes() != null) {
            existingJob.setNotes(jobRequest.getNotes());
        }
        if (jobRequest.getDateApplied() != null) {
            existingJob.setDateApplied(java.time.LocalDateTime.parse(jobRequest.getDateApplied()));
        }

        jobRepository.save(existingJob);
        log.info("Job updated successfully with ID: {}", existingJob.getJobId());
        return existingJob;
    }
}
